title: "Tide Docs"
remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/tide-logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "Source Code":
    - "//github.com/wptide/docs"
  "Blog":
    - "//make.wordpress.org/tide"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content 
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Distributed by an <a href=\"https://github.com/jeffpaul/docs/tree/gh-pages/LICENSE.md\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/jeffpaul/docs" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Change default color scheme to use Tide color scheme
color_scheme: tide
